flags:
  mysql-haskell: {}
packages:
- '.'
extra-deps: ['binary-parsers-0.2.4.0', 'wire-streams-0.1.1.0', {git: "https://github.com/naushadh/word24", commit: "1cc234d53923c270e888fdeac868c34306c43c70"}]
resolver: lts-20

# TODO go trough all depedencies, see why they don't work
allow-newer: true
